// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  modules: [
    '@nuxt/content',
    '@nuxt/fonts',
    '@nuxt/image',
    '@nuxtjs/seo',
    '@nuxt/eslint',
  ],
  css: ['~/assets/css/tokens.css'],
  // Self-hosted via @nuxt/fonts (resolved from Google at build time, served
  // from /_fonts) — no third-party request at runtime.
  fonts: {
    families: [
      { name: 'Moul', provider: 'google', weights: [400], global: true },
      { name: 'Moulpali', provider: 'google', weights: [400], global: true },
      { name: 'Taprom', provider: 'google', weights: [400], global: true },
      { name: 'Battambang', provider: 'google', weights: [300, 400, 700], global: true },
      { name: 'Cinzel', provider: 'google', weights: [400, 600], global: true },
      { name: 'IBM Plex Mono', provider: 'google', weights: [400], global: true },
    ],
    defaults: { subsets: ['khmer', 'latin'] },
  },
  app: {
    pageTransition: { name: 'page', mode: 'out-in' },
    head: {
      // Angkor Wat mark, generated by scripts/angkor-logo.py.
      link: [
        { rel: 'icon', href: '/favicon.ico', sizes: '48x48' },
        { rel: 'icon', href: '/favicon.svg', type: 'image/svg+xml' },
        { rel: 'apple-touch-icon', href: '/apple-touch-icon.png' },
        { rel: 'manifest', href: '/site.webmanifest' },
      ],
      meta: [{ name: 'theme-color', content: '#0C1410' }],
    },
  },
  image: {
    // Optimize local images only — everything lives under public/images/.
    provider: 'ipx',
    quality: 85,
    densities: [1, 2],
  },
  nitro: {
    prerender: {
      // The static heritage site lives in public/static/ and is copied as-is;
      // it is not a Nuxt route, so skip it during prerendering.
      ignore: ['/static/'],
      // All 26 content pages are known at build time (15 era + 11 heritage),
      // so prerender the detail routes as real static HTML — a plain static
      // host (npx serve, Netlify, GitHub Pages) serves them without a fallback.
      routes: [
        '/timeline', '/credits', '/calendar', '/map',
        '/era/era-0', '/era/era-1', '/era/era-2', '/era/era-3', '/era/era-4',
        '/era/era-5', '/era/era-6', '/era/era-7', '/era/era-8', '/era/era-9',
        '/era/era-10', '/era/era-11', '/era/era-12', '/era/era-13', '/era/era-14',
        '/heritage/amok', '/heritage/angkor', '/heritage/apsara', '/heritage/chapei',
        '/heritage/koh-ker', '/heritage/krama', '/heritage/lbokator',
        '/heritage/memorial-sites', '/heritage/preah-vihear',
        '/heritage/sambor-prei-kuk', '/heritage/sbek-thom',
      ],
    },
  },
  typescript: {
    tsConfig: {
      compilerOptions: {
        // The Suriyakati engine (app/utils/khmer-calendar.ts) is a verified,
        // runtime-tested port that intentionally indexes fixed-size lookup
        // arrays by integer month/tithi keys. noUncheckedIndexedAccess only adds
        // advisory undefined-noise there without catching real bugs (correctness
        // is proven by the Vitest suite), so we relax it and keep all other
        // strict checks on.
        noUncheckedIndexedAccess: false,
      },
    },
  },
  vite: {
    // Pre-bundle the map libraries at dev-server start; they are imported
    // lazily, and discovering them mid-session makes Vite re-optimise and
    // serve "504 Outdated Optimize Dep" for the in-flight import.
    optimizeDeps: { include: ['maplibre-gl'] },
    // MapLibre 6 runs its tile parser in a module worker; PlaceMap passes the
    // bundled worker's URL (…-worker.mjs?worker&url) to setWorkerUrl().
    worker: { format: 'es' },
  },
  devtools: { enabled: true },
  compatibilityDate: '2024-04-03',
  site: {
    url: 'https://khmer-heritage.example',
    name: 'បេតិកភណ្ឌខ្មែរ — Khmer Heritage',
    description: 'បេតិកភណ្ឌរស់រវើករបស់ខ្មែរ — ស្ថាបត្យកម្ម របាំ តន្ត្រី ម្ហូប និងប្រតិទិនចន្ទគតិ។',
  },
})
