// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  modules: [
    '@nuxt/content',
    '@nuxt/fonts',
    '@nuxt/image',
    '@nuxtjs/seo',
    '@nuxt/eslint',
    '@vite-pwa/nuxt',
  ],
  css: ['~/assets/css/tokens.css'],
  // Self-hosted via @nuxt/fonts (resolved from Google at build time, served
  // from /_fonts) — no third-party request at runtime.
  fonts: {
    families: [
      { name: 'Moul', provider: 'google', weights: [400], global: true },
      { name: 'Moulpali', provider: 'google', weights: [400], global: true },
      { name: 'Taprom', provider: 'google', weights: [400], global: true },
      { name: 'Battambang', provider: 'google', weights: [300, 400, 700], global: true },
      { name: 'Cinzel', provider: 'google', weights: [400, 600], global: true },
      { name: 'IBM Plex Mono', provider: 'google', weights: [400], global: true },
    ],
    defaults: { subsets: ['khmer', 'latin'] },
  },
  app: {
    pageTransition: { name: 'page', mode: 'out-in' },
    head: {
      // viewport-fit=cover: in the installed app the page runs under the
      // status bar / notch; the header pads itself with env(safe-area-inset-*).
      viewport: 'width=device-width, initial-scale=1, viewport-fit=cover',
      // Angkor Wat mark, generated by scripts/angkor-logo.py. The web app
      // manifest link comes from <NuxtPwaManifest /> (app.vue).
      link: [
        { rel: 'icon', href: '/favicon.ico', sizes: '48x48' },
        { rel: 'icon', href: '/favicon.svg', type: 'image/svg+xml' },
        { rel: 'apple-touch-icon', href: '/apple-touch-icon.png' },
      ],
      meta: [
        { name: 'theme-color', content: '#0C1410' },
        // iOS home-screen app: full screen, content under a translucent status bar
        { name: 'mobile-web-app-capable', content: 'yes' },
        { name: 'apple-mobile-web-app-capable', content: 'yes' },
        { name: 'apple-mobile-web-app-status-bar-style', content: 'black-translucent' },
        { name: 'apple-mobile-web-app-title', content: 'បេតិកភណ្ឌខ្មែរ' },
      ],
    },
  },
  image: {
    // Local images only (public/images/). On Vercel, Vercel's image CDN
    // resizes, converts to AVIF/WebP and caches at the edge; elsewhere IPX
    // (prerendered to static files). Without this, every image on Vercel went
    // through the serverless function running IPX + sharp: cold starts on the
    // first view of each size.
    provider: process.env.VERCEL ? 'vercel' : 'ipx',
    quality: 85,
    densities: [1, 2],
    // The Vercel provider only serves widths listed here (anything else is
    // rounded up): every NuxtImg width in the app, at 1× and 2×.
    screens: {
      w104: 104, w160: 160, w208: 208, xs: 320, w420: 420, w480: 480, sm: 640, w720: 720,
      md: 768, w840: 840, w960: 960, lg: 1024, xl: 1280, w1440: 1440, xxl: 1536, w1920: 1920,
    },
  },
  nitro: {
    // Vercel image CDN: keep optimised images for 30 days (default 5 min).
    vercel: { config: { images: { minimumCacheTTL: 2592000 } } },
    prerender: {
      // The static heritage site lives in public/static/ and is copied as-is;
      // it is not a Nuxt route, so skip it during prerendering.
      ignore: ['/static/'],
      // All 26 content pages are known at build time (15 era + 11 heritage),
      // so prerender the detail routes as real static HTML — a plain static
      // host (npx serve, Netlify, GitHub Pages) serves them without a fallback.
      // The two index pages must be listed too: without them /era and
      // /heritage had no HTML (a 404 on a static host, and 86 link-checker
      // errors, since every page links to them from the nav).
      routes: [
        '/', '/era', '/heritage', '/offline',
        '/timeline', '/credits', '/calendar', '/map',
        '/era/era-0', '/era/era-1', '/era/era-2', '/era/era-3', '/era/era-4',
        '/era/era-5', '/era/era-6', '/era/era-7', '/era/era-8', '/era/era-9',
        '/era/era-10', '/era/era-11', '/era/era-12', '/era/era-13', '/era/era-14',
        '/heritage/amok', '/heritage/angkor', '/heritage/apsara', '/heritage/chapei',
        '/heritage/koh-ker', '/heritage/krama', '/heritage/lbokator',
        '/heritage/memorial-sites', '/heritage/preah-vihear',
        '/heritage/sambor-prei-kuk', '/heritage/sbek-thom',
      ],
    },
  },
  routeRules: {
    // The offline fallback page is for the service worker only.
    '/offline': { robots: false },
    // CDN caching on Vercel. Hashed build files (/_nuxt) are already immutable;
    // these paths are not content-hashed, so they get a long max-age plus
    // stale-while-revalidate (a redeploy with a changed photo still shows up).
    '/images/**': { headers: { 'cache-control': 'public, max-age=2592000, stale-while-revalidate=604800' } },
    '/_ipx/**': { headers: { 'cache-control': 'public, max-age=2592000, stale-while-revalidate=604800' } },
    '/icons/**': { headers: { 'cache-control': 'public, max-age=604800, stale-while-revalidate=604800' } },
    '/fonts/**': { headers: { 'cache-control': 'public, max-age=31536000, immutable' } },
    '/_fonts/**': { headers: { 'cache-control': 'public, max-age=31536000, immutable' } },
    '/data/**': { headers: { 'cache-control': 'public, max-age=3600, stale-while-revalidate=604800' } },
  },
  // ---------- Installable app + offline (service worker) ----------
  pwa: {
    registerType: 'prompt', // a new version waits for the reader's OK (components/PwaPrompt.vue)
    client: { installPrompt: true, periodicSyncForUpdates: 60 * 60 },
    manifest: {
      id: '/',
      name: 'បេតិកភណ្ឌខ្មែរ — Khmer Heritage',
      short_name: 'បេតិកភណ្ឌខ្មែរ',
      description: 'ប្រាសាទ ប្រវត្តិសាស្ត្រ បេតិកភណ្ឌរស់ និងប្រតិទិនចន្ទគតិខ្មែរ — អានបាន សូម្បីតែក្រៅបណ្ដាញ។',
      lang: 'km',
      dir: 'ltr',
      start_url: '/?source=pwa',
      scope: '/',
      display: 'standalone',
      orientation: 'any',
      theme_color: '#0C1410',
      background_color: '#0C1410',
      categories: ['education', 'travel', 'books'],
      launch_handler: { client_mode: 'navigate-existing' },
      icons: [
        { src: '/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
        { src: '/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
        // full-bleed, logo inside the safe zone: Android crops it to its own shape
        { src: '/icons/maskable-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
        { src: '/favicon.svg', sizes: 'any', type: 'image/svg+xml', purpose: 'any' },
      ],
      // long-press the app icon (icons: scripts/pwa-icons.mjs)
      shortcuts: [
        { name: 'ផែនទីប្រាសាទ', short_name: 'ផែនទី', url: '/map?source=pwa', icons: [{ src: '/icons/shortcut-map.png', sizes: '96x96', type: 'image/png' }] },
        { name: 'ខ្សែប្រវត្តិសាស្ត្រ', short_name: 'ប្រវត្តិសាស្ត្រ', url: '/timeline?source=pwa', icons: [{ src: '/icons/shortcut-timeline.png', sizes: '96x96', type: 'image/png' }] },
        { name: 'បេតិកភណ្ឌរស់', short_name: 'បេតិកភណ្ឌ', url: '/heritage?source=pwa', icons: [{ src: '/icons/shortcut-heritage.png', sizes: '96x96', type: 'image/png' }] },
        { name: 'ប្រតិទិនចន្ទគតិ', short_name: 'ប្រតិទិន', url: '/calendar?source=pwa', icons: [{ src: '/icons/shortcut-calendar.png', sizes: '96x96', type: 'image/png' }] },
      ],
    },
    workbox: {
      // Saved at install (~4.5 MB): every prerendered page + its payload, the
      // app code, fonts, icons, the temple index with every temple's history,
      // and the province/district boundaries — so the whole site, map list,
      // search and temple cards included, works offline. Photos, map tiles and
      // commune boundaries are saved as they are viewed (runtimeCaching below).
      globPatterns: [
        '**/*.{js,css,html,woff2,svg,ico,png,webmanifest}',
        '__nuxt_content/**/*',
        'data/temples/index.json',
        'data/temples/detail/*.json', // every temple's history, ~280 KB
        'data/cambodia-admin/provinces.geojson',
        'data/cambodia-admin/districts.geojson',
      ],
      globIgnores: ['static/**', '_ipx/**', 'images/**', '__link-checker__/**'],
      maximumFileSizeToCacheInBytes: 3 * 1024 * 1024,
      // Prerendered pages live at era/era-4/index.html but are requested as
      // /era/era-4 — precache them under the URL the app uses.
      manifestTransforms: [async (entries) => ({
        manifest: entries.map((e) => e.url === 'index.html'
          ? { ...e, url: '/' }
          : e.url.endsWith('/index.html') ? { ...e, url: `/${e.url.slice(0, -'/index.html'.length)}` } : e),
        warnings: [],
      })],
      // Payloads are fetched as _payload.json?<build id>, and /map?place=… is
      // the /map page: match precached files whatever the query string.
      ignoreURLParametersMatching: [/.*/],
      // Pages that are not precached go to the network; offline, /offline.
      navigateFallback: null,
      cleanupOutdatedCaches: true,
      // Patterns are RegExps, not functions: the service-worker build minifies
      // function patterns and drops their destructured parameters. (A RegExp
      // on another origin must match from the start of the URL.)
      runtimeCaching: [
        {
          urlPattern: ({ request }) => request.mode === 'navigate',
          handler: 'NetworkOnly',
          options: { precacheFallback: { fallbackURL: '/offline' } },
        },
        {
          // hashed build files not precached (Nuxt Content's sqlite wasm)
          urlPattern: /\/_nuxt\//,
          handler: 'CacheFirst',
          options: { cacheName: 'kh-build', expiration: { maxEntries: 40 } },
        },
        {
          urlPattern: /\/(?:_ipx\/|images\/|_vercel\/image\b)/,
          handler: 'CacheFirst',
          options: { cacheName: 'kh-images', expiration: { maxEntries: 300, maxAgeSeconds: 60 * 24 * 3600, purgeOnQuotaError: true } },
        },
        {
          // temple detail per province, commune boundaries
          urlPattern: /\/data\//,
          handler: 'StaleWhileRevalidate',
          options: { cacheName: 'kh-data', expiration: { maxEntries: 300, purgeOnQuotaError: true } },
        },
        {
          // the basemap's TileJSON points at versioned tile URLs: keep it fresh
          urlPattern: /^https:\/\/tiles\.openfreemap\.org\/planet$/,
          handler: 'NetworkFirst',
          options: { cacheName: 'kh-map-style', networkTimeoutSeconds: 4, cacheableResponse: { statuses: [200] } },
        },
        {
          // vector tiles + label glyphs: areas you have looked at stay on the device
          urlPattern: /^https:\/\/tiles\.openfreemap\.org\//,
          handler: 'CacheFirst',
          options: { cacheName: 'kh-map-tiles', cacheableResponse: { statuses: [200] }, expiration: { maxEntries: 3000, maxAgeSeconds: 30 * 24 * 3600, purgeOnQuotaError: true } },
        },
        {
          urlPattern: /^https:\/\/s3\.amazonaws\.com\/elevation-tiles-prod\//,
          handler: 'CacheFirst',
          options: { cacheName: 'kh-terrain', cacheableResponse: { statuses: [200] }, expiration: { maxEntries: 500, maxAgeSeconds: 90 * 24 * 3600, purgeOnQuotaError: true } },
        },
        {
          urlPattern: /^https:\/\/server\.arcgisonline\.com\//,
          handler: 'CacheFirst',
          options: { cacheName: 'kh-satellite', cacheableResponse: { statuses: [200] }, expiration: { maxEntries: 500, maxAgeSeconds: 30 * 24 * 3600, purgeOnQuotaError: true } },
        },
      ],
    },
  },
  // Open Graph images are not used (no defineOgImage anywhere). Left on, the
  // module bundles @takumi-rs/core with its per-platform native binaries into
  // the server build, which fails under pnpm ("ENOENT … core-win32-x64-msvc":
  // only the current platform's binary is installed).
  ogImage: { enabled: false },
  linkChecker: {
    // /map?place=… links are the prerendered /map page with a query the page
    // reads client-side; the checker only knows the bare /map and reports them
    // as 404s, so skip the query variants.
    excludeLinks: [/^\/map\?/],
  },
  typescript: {
    tsConfig: {
      compilerOptions: {
        // The Suriyakati engine (app/utils/khmer-calendar.ts) is a verified,
        // runtime-tested port that intentionally indexes fixed-size lookup
        // arrays by integer month/tithi keys. noUncheckedIndexedAccess only adds
        // advisory undefined-noise there without catching real bugs (correctness
        // is proven by the Vitest suite), so we relax it and keep all other
        // strict checks on.
        noUncheckedIndexedAccess: false,
      },
    },
  },
  vite: {
    // Pre-bundle the map libraries at dev-server start; they are imported
    // lazily, and discovering them mid-session makes Vite re-optimise and
    // serve "504 Outdated Optimize Dep" for the in-flight import.
    optimizeDeps: { include: ['maplibre-gl'] },
    // MapLibre 6 runs its tile parser in a module worker; PlaceMap passes the
    // bundled worker's URL (…-worker.mjs?worker&url) to setWorkerUrl().
    worker: { format: 'es' },
  },
  devtools: { enabled: true },
  compatibilityDate: '2024-04-03',
  // Used for canonical URLs, the sitemap, robots.txt, og:url and structured data.
  site: {
    url: 'https://kh-historic.vercel.app',
    name: 'បេតិកភណ្ឌខ្មែរ — Khmer Heritage',
    description: 'ប្រាសាទប្រវត្តិសាស្ត្រទូទាំងកម្ពុជា ខ្សែប្រវត្តិសាស្ត្រខ្មែរ បេតិកភណ្ឌរស់ និងប្រតិទិនចន្ទគតិ — Khmer temples, history, living heritage and the lunar calendar.',
    defaultLocale: 'km',
    indexable: true,
  },
  schemaOrg: {
    identity: {
      type: 'Organization',
      name: 'បេតិកភណ្ឌខ្មែរ — Khmer Heritage',
      alternateName: 'Khmer Heritage',
      logo: '/icon-512.png',
    },
  },
})
